# Generated by Django 5.0.4 on 2024-07-31 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_schedule_title'),
        ('subject', '0007_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='subject.subject'),
        ),
    ]
